[project]
name = "postech-genai-openai-bridge"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn>=0.34.0",
    "requests>=2.32.0",
    "python-multipart>=0.0.20",
    "python-dotenv>=1.0.0",
]
